### ISSUE TITLE
TypeError: Cannot read property 'brokerLbUrl' of undefined

### ISSUE THREAD

**Issue by L-U-C-K-Y** [qiscus/qiscus-sdk-web-core#59]
Dear Qiscus Team

I receive the following error in our react app:

```typescript
TypeError
Cannot read property 'brokerLbUrl' of undefined
```

At:

```typescript
 * The buffer module from node.js, for the browser.
 *
 * @author   Feross Aboukhadijeh <http://feross.org>
 * @license  MIT
 */
{snip} (e),t}},se=function(){function e(t,r,n,i){var o,a=this,c=i.brokerLbUrl,f=i.enableLb;l()(this,e),d()(this,"subscribtionBuffer",[]),d()(this," {snip}
//# sourceMappingURL=qiscus-sdk-core.min.js.map
```

Qiscus Version: `"qiscus-sdk-core": "2.9.10"`

Do you have a clue what this could be?

**Comment by adicatur** [comment]
Hi @lucbas can you share prior process or steps on how do you get this error?

**Comment by lucbas** [comment]
Hi @adicatur,

We were just initializing the Qiscus SDK Core in our react app and were not executing any specific actions. Here is more detailed log of sentry:

![image](https://user-images.githubusercontent.com/14868134/88374218-a7600680-cd99-11ea-874b-69912aae57db.png)

**Comment by adicatur** [comment]
Hi @lucbas thanks for the screenshot,
can you share your code on how do you initializing? or you can share to this email: catur@qiscus.com 

`Would you recommend upgrading to 3.0.0? I saw that there are breaking changes, but it's not described what they are breaking.`

that's correct that 3.0.0 is breaking changes, it uses typescript and it's refactoring version, this version is cleaner and also has ability to support multiple appID :)

**Comment by lucbas** [comment]
Sure thing, I have sent you an email.

We initialize Qiscus as follows:

```
export const init = () => {
  qiscus.init({
    AppId: appId,
  });
};
```

Where the appId comes from an environment variable.

Most of the times, the healthchecks that Qiscus performs work, but there are some instances where I get the above error.

**Comment by adicatur** [comment]
Ok thanks,

Just wondering on how the qiscus init being called, we see the screenshot somehow every time when the `realtime-lb` called three time at same time it shows undefined

**Comment by prazeblaze** [comment]
I was also facing this problem, downgrading the SDK to version 2.9.7 fixed the issue for me.

**Comment by adicatur** [comment]
Hi @prazeblaze

Ok, we still working on to fix this issue will let you know the update

**Comment by adicatur** [comment]
Hi @prazeblaze @L-U-C-K-Y 

We just released the latest version for fixing this issue, can you try using our latest version? you can find the changelog here: https://github.com/qiscus/qiscus-sdk-web-core/releases/tag/v2.9.12

**Comment by L-U-C-K-Y** [comment]
Thanks @adicatur, I have merged it into our code base and will update this thread after checking the stats.

**Comment by L-U-C-K-Y** [comment]
Looking good so far from my side, @prazeblaze is it also resolved for you?
