### ISSUE TITLE
ReferenceError: Can't find variable: localStorage

### ISSUE THREAD

**Issue by pandamako** [qiscus/qiscus-sdk-web-core#61]
Hello.

I use qiscus-sdk-core@2.9.12 with react native and I receive

```
ReferenceError: Can't find variable: localStorage

events.on$argument_1
    qiscus-sdk-core.min.js:14:252343
slice.map$argument_0
    qiscus-sdk-core.min.js:14:205948
map
    [native code]:0
slice.map$argument_0
    qiscus-sdk-core.min.js:14:205934
setInterval$argument_0
    qiscus-sdk-core.min.js:14:256954
_callTimer
    JSTimers.js:146:14
callTimers
    JSTimers.js:399:17
callFunctionReturnFlushedQueue
    [native code]:0
```

I looked up last commits and found what it was added at https://github.com/qiscus/qiscus-sdk-web-core/commit/49b44b05f1ff861e97a926051961f76d28319c6f
ReactNative does not have localStorage at all.

**Comment by adicatur** [comment]
Hello @pandamako ,
We're sorry for the inconvenience. The localstorage was added to fix comment status issue for web and it's indeed affected the react native version. For temporary solution you can try adding polyfill for it. You could try this.
   npm install localstorage-polyfill
and then in App.js
   import 'localstorage-polyfill';
Hope it helps.

**Comment by pandamako** [comment]
Thanks, temporary solution working.
