### ISSUE TITLE
Document Breaking Changes of "Qiscus Chat SDK Javascript 3.0.0"

### ISSUE THREAD

**Issue by L-U-C-K-Y** [qiscus/qiscus-sdk-web-core#64]
Dear Qiscus Team

You are mentioning breaking changes when upgrading to 3.0.0.

Can you please document them in the release notes or in the README so that we can prepare the upgrade?

Could I also kindly ask you what the difference between 2.9.X and 3.0.0 are?
Should we upgrade and what are the things we need to change?

Thanks a lot!

**Comment by L-U-C-K-Y** [comment]
Hi all,

Any follow-up here, safe to update?

**Comment by adicatur** [comment]
Hi @L-U-C-K-Y , 

For the docs on how to migrate 3.0.0 will deliver next week on Tuesday

**Comment by adicatur** [comment]
Hi @L-U-C-K-Y 
You can find the migration guide from v2.9.x to v3.0.x in this docs:
https://github.com/qiscus/qiscus-sdk-web-core/blob/v3/MIGRATION_GUIDE.md

**Comment by L-U-C-K-Y** [comment]
Fantastic, thank you very much!
