### ISSUE TITLE
getNonce() return null on cordova build iOS

### ISSUE THREAD

**Issue by ramzitm91** [qiscus/qiscus-sdk-web-core#70]
on my hybrid project, when I run it on web or android device, it all work like charm.
But on iOS device, I found this issue:

![Screen Shot 2021-01-13 at 22 51 22](https://user-images.githubusercontent.com/19144081/104604172-c340c700-56af-11eb-86c6-9d2082b63103.png)
is there any additional setting when using getNonce() function on iOS device?

**Comment by herlambangbp-lab** [comment]
hi bro

**Comment by adicatur** [comment]
cc @apiep

**Comment by apiep** [comment]
Hi, sorry for the inconvenience but we are unable to reproduce the issue, here is our repository for reproducing this issue https://github.com/apiep/qiscus-chat-sdk-cordova-sample

I will close this issue for now, if this issue still persist, please make a repository which will produce this issue just like mine. Cheers :)

Oh and feel free to reopen this issue by then
